import type {Plan} from './free-assistant.ts';
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function printablePlanHTML({name,date,logoUrl,plan}:{name:string;date:string;logoUrl:string;plan:Plan}):string {
 if(!plan.meals.length)throw Error('O plano ainda não tem refeições salvas.');
 const logo=new URL(logoUrl);if(!['https:','http:'].includes(logo.protocol))throw Error('Logo inválida.');
 return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Plano alimentar - ${escape(name)}</title><style>
 @page{size:A4;margin:15mm 14mm}*{box-sizing:border-box}body{font:11pt/1.45 Arial,sans-serif;color:#264a49;background:#fff;margin:0}header{display:flex;align-items:center;gap:14px;border-bottom:2px solid #168b87;padding-bottom:12px}header img{width:65px;height:65px;object-fit:contain}header h1{font-size:17pt;margin:0;color:#276e61}header p{font-size:9pt;margin:4px 0 0}header div{flex:1}.patient{margin:16px 0;padding:12px;background:#f2f9f4;border-left:4px solid #78b63a}.patient p{margin:2px 0}.title{font-size:13pt;color:#168b87;margin:16px 0 12px}.meal{margin:0 0 16px;break-inside:avoid;border:1px solid #dbe9e1;border-radius:6px;overflow:hidden}.meal h2{font-size:11pt;background:#276e61;color:#fff;margin:0;padding:8px 12px}.meal p{margin:0;padding:12px;white-space:pre-wrap;overflow-wrap:anywhere}.instructions{border-top:2px solid #168b87;margin-top:20px;padding-top:12px}.instructions h2{font-size:12pt;color:#276e61;margin:0 0 8px}.instructions p{white-space:pre-wrap;overflow-wrap:anywhere;margin:0}footer{font-size:8pt;margin-top:25px;padding-top:10px;border-top:1px solid #dbe9e1;color:#607e75}.actions{padding:14px;margin:0 0 18px;background:#f2f9f4}.actions button{font:inherit;padding:10px 16px;background:#276e61;color:white;border:0;border-radius:8px;cursor:pointer}.actions p{margin:8px 0;font-size:10pt}@media screen{body{max-width:850px;margin:24px auto;padding:20px}}@media print{.actions{display:none}body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
 </style></head><body><div class="actions"><button onclick="window.print()">Imprimir / Salvar como PDF</button><p>No destino da impressão, escolha Salvar como PDF para baixar o documento.</p></div><header><img src="${escape(logo.href)}" alt="Nutricionista Marakesia Nascimento"><div><h1>Marakesia Nascimento</h1><p>Nutricionista - CRN 11-6356</p></div></header><section class="patient"><p><strong>Paciente:</strong> ${escape(name)}</p><p><strong>Data:</strong> ${escape(date)}</p></section><h2 class="title">${escape(plan.title)}</h2>${plan.meals.map(m=>`<section class="meal"><h2>${escape(m.time||'Refeição')} - ${escape(m.label)}</h2><p>${escape(m.foods)}</p></section>`).join('')}${plan.instructions?`<section class="instructions"><h2>Orientações</h2><p>${escape(plan.instructions)}</p></section>`:''}<footer>Marakesia Nascimento - CRN 11-6356 · NutriMara</footer><script>window.addEventListener('load',()=>window.print(),{once:true});</script></body></html>`;
}
